export const KIBIBYTE = 1_024;
export const MEBIBYTE = KIBIBYTE * KIBIBYTE;

const MAX_ENCODED_YJS_STATE_MEBIBYTES = 10;
const MAX_WS_FRAME_MEBIBYTES = 16;

export const MAX_NODE_TITLE_CHARACTERS = 120;
export const MAX_COMPONENT_DESCRIPTION_CHARACTERS = 2_000;
export const MAX_TECHNOLOGY_CHARACTERS = 80;
export const MAX_CONTENT_BODY_CHARACTERS = 20_000;
export const MAX_EXTERNAL_URL_CHARACTERS = 2_048;
export const MAX_EDGE_LABEL_CHARACTERS = 160;
export const MAX_EDGE_PROTOCOL_CHARACTERS = 40;
export const MAX_BOUNDARY_TITLE_CHARACTERS = 120;
export const MAX_STEP_TITLE_CHARACTERS = 120;
export const MAX_STEP_NOTES_CHARACTERS = 4_000;

export const MIN_STEP_ORDER = -1_000_000;
export const MAX_STEP_ORDER = 1_000_000;
export const MAX_STEP_REFERENCES = 500;

export const MAX_GRAPH_COORDINATE = 100_000;
export const MIN_NODE_WIDTH = 160;
export const MAX_NODE_WIDTH = 1_600;
export const MIN_NODE_HEIGHT = 100;
export const MAX_NODE_HEIGHT = 1_200;
export const MAX_RECT_DIMENSION = 20_000;

export const MAX_LIVE_NODES = 500;
export const MAX_LIVE_EDGES = 1_000;
export const MAX_LIVE_BOUNDARIES = 50;
export const MAX_LIVE_PRESENTATION_STEPS = 50;

export const MAX_ENCODED_YJS_STATE_BYTES = MAX_ENCODED_YJS_STATE_MEBIBYTES * MEBIBYTE;
export const MAX_CLIENT_UPDATE_BYTES = MEBIBYTE;
export const MAX_WS_FRAME_BYTES = MAX_WS_FRAME_MEBIBYTES * MEBIBYTE;

export const MAX_PRESENCE_SELECTED_IDS = 100;
export const MAX_DRAG_PREVIEW_POSITIONS = 100;
