export const KIBIBYTE = 1_024;
export const MEBIBYTE = KIBIBYTE * KIBIBYTE;

const MAX_ENCODED_YJS_STATE_MEBIBYTES = 10;
const MAX_WS_FRAME_MEBIBYTES = 16;

export const MAX_NODE_TITLE_CHARACTERS = 120;
export const MAX_COMPONENT_DESCRIPTION_CHARACTERS = 2_000;
export const MAX_TECHNOLOGY_CHARACTERS = 80;
export const MAX_CONTENT_BODY_CHARACTERS = 20_000;
export const MAX_EXTERNAL_URL_CHARACTERS = 2_048;
export const MAX_EDGE_LABEL_CHARACTERS = 160;
export const MAX_EDGE_PROTOCOL_CHARACTERS = 40;
export const MAX_BOUNDARY_TITLE_CHARACTERS = 120;
export const MAX_STEP_TITLE_CHARACTERS = 120;
export const MAX_STEP_NOTES_CHARACTERS = 4_000;

export const MIN_STEP_ORDER = -1_000_000;
export const MAX_STEP_ORDER = 1_000_000;
export const MAX_STEP_REFERENCES = 500;

export const MAX_GRAPH_COORDINATE = 100_000;
export const MIN_NODE_WIDTH = 160;
export const MAX_NODE_WIDTH = 1_600;
export const MIN_NODE_HEIGHT = 100;
export const MAX_NODE_HEIGHT = 1_200;
export const MAX_RECT_DIMENSION = 20_000;

export const MAX_LIVE_NODES = 500;
export const MAX_LIVE_EDGES = 1_000;
export const MAX_LIVE_BOUNDARIES = 50;
export const MAX_LIVE_PRESENTATION_STEPS = 50;

export const MAX_ENCODED_YJS_STATE_BYTES = MAX_ENCODED_YJS_STATE_MEBIBYTES * MEBIBYTE;
export const MAX_CLIENT_UPDATE_BYTES = MEBIBYTE;
export const MAX_WS_FRAME_BYTES = MAX_WS_FRAME_MEBIBYTES * MEBIBYTE;

export const MAX_PRESENCE_SELECTED_IDS = 100;
export const MAX_DRAG_PREVIEW_POSITIONS = 100;
export const MAX_PRESENCE_SELECTION_COUNT =
  MAX_LIVE_NODES + MAX_LIVE_EDGES + MAX_LIVE_BOUNDARIES + MAX_LIVE_PRESENTATION_STEPS;
export const MAX_PRESENCE_USER_NAME_CHARACTERS = 120;
export const MAX_PRESENCE_USER_ID_CHARACTERS = 256;
export const MAX_WS_ERROR_MESSAGE_CHARACTERS = 256;

export const MAX_BOARD_CONNECTIONS = 10;
export const MAX_ACTIVE_ROOMS = 20;
export const CONTENT_UPDATES_PER_SECOND = 20;
export const CONTENT_UPDATE_BURST = 40;
export const PRESENCE_UPDATES_PER_SECOND = 15;
export const MAX_VALIDATION_WORKERS = 2;
export const MAX_VALIDATION_QUEUE = 20;
export const VALIDATION_TIMEOUT_MS = 2_000;
export const HELLO_TIMEOUT_MS = 5_000;
export const WS_PING_INTERVAL_MS = 15_000;
export const WS_PONG_TIMEOUT_MS = 45_000;
export const PRESENCE_EXPIRY_MS = 30_000;
export const ROOM_IDLE_EVICTION_MS = 300_000;
export const SNAPSHOT_COMPACTION_UPDATES = 200;
export const SNAPSHOT_COMPACTION_INTERVAL_MS = 60_000;
export const RECONNECT_INITIAL_DELAY_MS = 1_000;
export const RECONNECT_MAX_DELAY_MS = 30_000;

export const MAX_BOARD_TITLE_CHARACTERS = 120;
export const MAX_BOARD_DESCRIPTION_CHARACTERS = 2_000;
export const MAX_ACTIVE_OWNED_BOARDS = 100;
export const DEFAULT_BOARD_PAGE_SIZE = 30;
export const MAX_BOARD_PAGE_SIZE = 100;
export const INVITE_TOKEN_BYTES = 32;
export const INVITE_LIFETIME_DAYS = 7;
export const IDEMPOTENCY_LIFETIME_HOURS = 24;

export const MAX_COMMENT_BODY_CHARACTERS = 4_000;
export const MAX_THREADS_PER_BOARD = 2_000;
export const MAX_COMMENTS_PER_THREAD = 500;

const MAX_IMPORT_FILE_MEBIBYTES = 5;
const MAX_IMPORT_REQUEST_OVERHEAD_KIBIBYTES = 64;
export const MAX_IMPORT_FILE_BYTES = MAX_IMPORT_FILE_MEBIBYTES * MEBIBYTE;
// The HTTP adapter must allow bounded JSON request overhead in addition to the file cap.
export const MAX_IMPORT_REQUEST_BYTES =
  MAX_IMPORT_FILE_BYTES + MAX_IMPORT_REQUEST_OVERHEAD_KIBIBYTES * KIBIBYTE;
export const MAX_CHECKPOINT_NAME_CHARACTERS = 120;
export const MAX_CHECKPOINTS_PER_BOARD = 100;
export const PRESENTER_LEASE_TIMEOUT_MS = 30_000;
export const MAX_EXPORT_IMAGE_SIDE_PIXELS = 8_192;
export const MAX_EXPORT_IMAGE_PIXELS = 32_000_000;
