export { ConfigurationError, loadApiConfig, type ApiConfig } from './api-config.js';
export {
  CONTENT_UPDATE_BURST,
  CONTENT_UPDATE_RATE_PER_SECOND,
  MAX_ACTIVE_ROOMS_PER_PROCESS,
  MAX_CONNECTIONS_PER_ROOM,
  MAX_VALIDATION_QUEUE_DEPTH,
  MAX_VALIDATION_WORKERS,
  PRESENCE_UPDATE_RATE_PER_SECOND,
  PUBLIC_BIND_HOST,
  VALIDATION_TIMEOUT_MS,
  WS_HANDSHAKE_TIMEOUT_MS,
  WS_PING_INTERVAL_MS,
  WS_PONG_TIMEOUT_MS,
} from './operational-defaults.js';
