export const PUBLIC_BIND_HOST = '0.0.0.0';

export const WS_HANDSHAKE_TIMEOUT_MS = 5_000;
export const WS_PING_INTERVAL_MS = 15_000;
export const WS_PONG_TIMEOUT_MS = 45_000;

export const VALIDATION_TIMEOUT_MS = CONTRACT_VALIDATION_TIMEOUT_MS;
export const MAX_VALIDATION_WORKERS = CONTRACT_MAX_VALIDATION_WORKERS;
export const MAX_VALIDATION_QUEUE_DEPTH = MAX_VALIDATION_QUEUE;

export const MAX_CONNECTIONS_PER_ROOM = 10;
export const MAX_ACTIVE_ROOMS_PER_PROCESS = 20;

export const CONTENT_UPDATE_RATE_PER_SECOND = 20;
export const CONTENT_UPDATE_BURST = 40;
export const PRESENCE_UPDATE_RATE_PER_SECOND = 15;

export const TYPEORM_POOL_MAX_DEFAULT = 10;
export const BETTER_AUTH_POOL_MAX_DEFAULT = 5;
export const DATABASE_CONNECTION_TIMEOUT_MS_DEFAULT = 10_000;
export const BETTER_AUTH_IDLE_TIMEOUT_MS_DEFAULT = 30_000;
import {
  MAX_VALIDATION_QUEUE,
  MAX_VALIDATION_WORKERS as CONTRACT_MAX_VALIDATION_WORKERS,
  VALIDATION_TIMEOUT_MS as CONTRACT_VALIDATION_TIMEOUT_MS,
} from '@archboard/contracts';
