import { z } from 'zod';

export const ERROR_CODES = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  BOARD_ARCHIVED: 'BOARD_ARCHIVED',
  ROOM_FULL: 'ROOM_FULL',
  SERVER_BUSY: 'SERVER_BUSY',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  DOCUMENT_INVALID: 'DOCUMENT_INVALID',
  DOCUMENT_LIMIT: 'DOCUMENT_LIMIT',
  SCHEMA_UNSUPPORTED: 'SCHEMA_UNSUPPORTED',
  UPDATE_ID_REUSED: 'UPDATE_ID_REUSED',
  CAUSAL_GAP: 'CAUSAL_GAP',
  PERSISTENCE_FAILED: 'PERSISTENCE_FAILED',
} as const;

export const errorCodeSchema = z.enum(ERROR_CODES);

export type ErrorCode = z.infer<typeof errorCodeSchema>;
