import { z } from 'zod';

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  // Transient contention/invalid-step/rate denial must not suspend the durable update stream.
  PRESENTER_DENIED: 'PRESENTER_DENIED',
  NOT_FOUND: 'NOT_FOUND',
  BOARD_ARCHIVED: 'BOARD_ARCHIVED',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  INVITE_UNAVAILABLE: 'INVITE_UNAVAILABLE',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_EXHAUSTED: 'INVITE_EXHAUSTED',
  RATE_LIMITED: 'RATE_LIMITED',
  TEMPORARILY_UNAVAILABLE: 'TEMPORARILY_UNAVAILABLE',
  ROOM_FULL: 'ROOM_FULL',
  SERVER_BUSY: 'SERVER_BUSY',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  DOCUMENT_INVALID: 'DOCUMENT_INVALID',
  DOCUMENT_LIMIT: 'DOCUMENT_LIMIT',
  SCHEMA_UNSUPPORTED: 'SCHEMA_UNSUPPORTED',
  UPDATE_ID_REUSED: 'UPDATE_ID_REUSED',
  CAUSAL_GAP: 'CAUSAL_GAP',
  PERSISTENCE_FAILED: 'PERSISTENCE_FAILED',
} as const;

export const errorCodeSchema = z.enum(ERROR_CODES);

export type ErrorCode = z.infer<typeof errorCodeSchema>;
